### ISSUE TITLE
About the COCO Dataset in the code

### ISSUE THREAD

**Issue by haoyutiantang** [abhi-iyer/visual-question-answering#3]
Hi. I am a green hand in VQA. I want to run your experiment ，But I don't know which dataset I should download in the picture. Could you please tell me?
![image](https://user-images.githubusercontent.com/34064792/100069833-24001000-2e74-11eb-8a26-c0d26c3fc368.png)

**Comment by abhi-iyer** [comment]
Use the 2017 train/val/test splits - we reference this when building the dataloader/dataset
