### ISSUE TITLE
How to deploy the model?

### ISSUE THREAD

**Issue by tihartmann** [abhi-iyer/visual-question-answering#4]
Hi, thanks for making the code and model available! 
I am trying to run the pre-trained model on unseen data, i.e., I would like to deploy the model so that I can input an image and a natural language question. Given these inputs, the model should then return an output. If I adopt the code from the sample() function of the ExperimentLoader class, it works fine unless the question contains (a) word(s) that is/are not in the vocabulary. 
Would you be able to share how this can be solved? Thank you!

**Comment by abhi-iyer** [comment]
The current implementation doesn't allow new vocab words, since the embedding from vocab size -> embedding dimension is fixed. 

You would likely need to retrain the model with the new words in question added to the vocabulary
